version: '3.9'
name : php-datetime
services:

    php:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ../:/var/www/